sass:
  style: :expanded # You might prefer to minify using :compressed

permalink: /:year/:month/:day/:title.html

url: http://veithen.github.io

debug: false

disqus_categories:
  tech: 3550508
  opinion: 3550509
